config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_list/index'
  get 'home/index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Add the following route for signing out
  resources :users, only: [:show]

  resources :foods # Add this line to generate the necessary routes for FoodsController

  resources :recipes, except: [:update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :public_recipes, except: [:update]
  resources :recipes do
    patch 'toggle_public', on: :member
  end
  resources :general_shopping_list, only: [:index]
  get 'general_shopping_list', to: 'general_shopping_list#index', as: 'general_shopping_list'

  # Defines the root path route ("/")
  root "home#index" # Set the home page route to the "index" action of the "home" controller
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id'
  has_many :foods, through: :recipe_foods

  accepts_nested_attributes_for :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(:foods).find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @foods = current_user.foods
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Recipe public status updated.'
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    # destroy all recipe_foods
    @recipe.recipe_foods&.destroy_all

    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/index.html.erb
<h1 class='header-title'>List of all recipes of <%= @user.name %></h1>
<h2><%= link_to 'Add Recipe', new_recipe_path %></h2>

<% if @recipes.empty? %>
  <h3 class='header-title'>No recipes found</h3>
<% else %>
  <% @recipes.each do |recipe| %>
    <div class='container-md recipe-container border border-dark'>
      <div class='recipe_name'>
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <% if can?(:destroy, recipe) %>
          <%= form_with(model: recipe, method: :delete, url: recipe_path(recipe)) do |form| %>
            <%= form.submit 'Delete', class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
      <div><%= recipe.description %></div>
    </div>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<h2 class = 'header-title'> New Recipe </h2>

<%= form_with(model: @recipe, url: recipes_path, method: :post ) do |f| %>

<div class="field mb-3 form">
    <%= f.label :name, class:'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mb-3 form">
    <%= f.label :preparation_time, class:'form-label'  %>
    <%= f.number_field :preparation_time, step: '0.25', value: 0.25, min: 0.25,class: 'form-control' %>
  </div>

  <div class="field mb-3 form">
    <%= f.label :cooking_time, class:'form-label'  %>
    <%= f.number_field :cooking_time, step: '0.25', value: 0.25, min: 0.25,class: 'form-control' %>
  </div>

  <div class="field mb-3 form">
    <%= f.label :description, class:'form-label'  %>
    <%= f.text_area :description, class: 'form-control' %>
  </div> 

  <div class="field mb-3 form">
    <%= f.label :public, class:'form-check-label'  %>
   <%= f.check_box :public, checked_value: true, unchecked_value: false, class: 'form-check-input' %>
  </div>

 
  <%= f.submit 'Create a recipe', class: 'btn btn-primary mb-3' %>

<%end%>

app/views/recipes/show.html.erb
<h2 class= 'header-title'> <%= @recipe.name%> </h2>

<div class= 'recipe container'>

<% if can?(:update,@recipe) || @recipe.public  %>
<div class = 'preparation-toggle'> 
<div> <p><strong> Preparation time: <%= @recipe.preparation_time %> <% if @recipe.preparation_time > 1 %> hours <% else %> hour <%end%> </strong> </p> </div>
<div> 
<% if can?(:update, @recipe) %>
  <%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch) do |form| %>
    <% if @recipe.public %>
      <%= form.submit 'Make Private', class: 'btn btn-danger' %>
    <% else %>
      <%= form.submit 'Make Public', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

</div>
</div>
<div class = 'preparation-toggle'>
<p> <strong> Cooking time: <%= @recipe.cooking_time %> <% if @recipe.cooking_time > 1 %> hours <% else %> hour <%end%> </strong></p>
</div>
<div class = 'preparation-toggle'>
<p><strong> Recipe steps:</strong> <%= @recipe.description %>  </p>
</div>


 <div class="preparation-toggle ">
<%= button_to "Generate shopping list", general_shopping_list_index_path, method: :get, class: "btn btn-primary generator " %>
<% if can?(:update, @recipe)%>
<%= button_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-primary generator" %>
<%end%>
</div> 

</div>


<table class="table table-bordered table-striped" id='recipe_table'>
<thead>
<tr>
<th> Food </th>
<th> Quantity </th>
<th> Value </th>
<th> Actions </th>
 </tr>
 </thead>
 <tbody>
 <%@recipe.recipe_foods.each do |recipe_food|%> 
 <tr>
  <td> <%= recipe_food.food.name %> </td>
   <td><%="#{recipe_food.quantity} #{recipe_food.food.measurement_unit}"%></td>
    <td><%= recipe_food.quantity * recipe_food.food.price %>$</td>
    <%if can?(:update,@recipe)%>
    <td class ='button-flex'><%= button_to 'Delete',recipe_recipe_food_path(@recipe,recipe_food),method: :delete, class: 'btn btn-danger' %><button class='btn btn-success'>Modify </button></td>
    <%end%>
  </tr>

 <%end%>
 </tbody>

<table>
<%else%>
<h2 class='header-title'> This recipe is private </h2>
<%end%>