config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_list/index'
  get 'home/index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Add the following route for signing out
  resources :users, only: [:show]

  resources :foods # Add this line to generate the necessary routes for FoodsController

  resources :recipes, except: [:update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :public_recipes, except: [:update]
  resources :recipes do
    patch 'toggle_public', on: :member
  end
  resources :general_shopping_list, only: [:index]
  get 'general_shopping_list', to: 'general_shopping_list#index', as: 'general_shopping_list'

  # Defines the root path route ("/")
  root "home#index" # Set the home page route to the "index" action of the "home" controller
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id'
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  # GET /foods or /foods.json
  def index
    @user = current_user
    @foods = @user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.recipe_foods&.destroy_all
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price, :user_id)
  end
end

app/views/foods/_food.html.erb
<table id="foods">
<div id="<%= dom_id food %>">
<tr>
  <th>Name</th>
  <th>Measurement unit</th>
  <th>Quantity</th>
  <th>Unit price</th>
  <th>Actions</th>
  <th>View</th>
</tr>
  <tr id="<%= dom_id food %>">
    <td class="table_data">
    <%= food.name %>
    </td>
    <td class="table_data"><%= food.measurement_unit %></td>
    <td class="table_data"><%= food.quantity %></td>
    <td class="table_data">$<%= food.price %></td>
    <td class="table_data"><%= button_to "Delete", food, method: :delete, class: "btn_delete" %></td>
    <td class="table_data"><%= link_to "Show", food, class: "btn_delete" %></td>
    </tr>
    
    </div>
    </table>

    </br>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
  
        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name, style: "display: block", class: "label" %>
      <%= form.text_field :name, required: true, class:"input" %>
    </div>
  
    <div class="field">
      <%= form.label :measurement_unit, style: "display: block", class: "label" %>
      <%= form.text_field :measurement_unit, required: true, class:"input" %>
    </div>
  
    <div class="field">
      <%= form.label :quantity, style: "display: block", class: "label" %>
      <%= form.number_field :quantity, required: true, class:"input" %>
    </div>
  
    <div class="field">
      <%= form.label :price, style: "display: block", class: "label" %>
      <%= form.text_field :price, required: true, class:"input" %>
    </div>
    
    <div>
    <%= form.submit "Create food", class: "btn-submit" %>
    </div>
  <% end %>

app/views/foods/edit.html.erb
<h1 class="food_title">Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<h1 class="food_title">Foods</h1>

<table id="foods">
  <tr>
    <th>Name</th>
    <th>Measurement unit</th>
    <th>Quantity</th>
    <th>Unit price</th>
    <th>Actions</th>
    <th>View</th>
  </tr>
  <% @foods.each do |food| %>
    <tr id="<%= dom_id food %>">
      <td class="table_data">
      <%= food.name %>
      </td>
      <td class="table_data"><%= food.measurement_unit %></td>
      <td class="table_data"><%= food.quantity %></td>
      <td class="table_data">$<%= food.price %></td>
      <td class="table_data"><%= button_to "Delete", food, method: :delete, class: "btn_delete" %></td>
      <td class="table_data"><%= link_to "Show", food, class: "btn_delete" %></td>
    </tr>
  <% end %>
  </table>

<%= link_to "Add food", new_food_path, class: "btn_new_food" %>

app/views/foods/new.html.erb
<h1 class="food_title">New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<h1 class="food_title">Show Food</h1>

<%= render @food %>

<div>
  <%= link_to "Back to foods", foods_path %>  |
  <%= link_to "Edit this food", edit_food_path(@food) %> 
</div>