config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_list/index'
  get 'home/index'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Add the following route for signing out
  resources :users, only: [:show]

  resources :foods # Add this line to generate the necessary routes for FoodsController

  resources :recipes, except: [:update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :public_recipes, except: [:update]
  resources :recipes do
    patch 'toggle_public', on: :member
  end
  resources :general_shopping_list, only: [:index]
  get 'general_shopping_list', to: 'general_shopping_list#index', as: 'general_shopping_list'

  # Defines the root path route ("/")
  root "home#index" # Set the home page route to the "index" action of the "home" controller
end

app/views/layouts/_navbar.html.erb
<header>
    <nav>
        <ul class="nav_list">
        <%= link_to "Home", root_path, class: "nav-item mobile-home" %>
        <%= link_to "Foods", foods_path, class: "nav-item" %>
        <%= link_to "Recipes", recipes_path, class: "nav-item" %>
        <%= link_to "Public Recipes", public_recipes_path, class: "nav-item" %>
        <%= link_to "General Shoping List", general_shopping_list_path, class: "nav-item" %>
            <% if user_signed_in? %>
            <li class="sign_out">
            <p class="nav_name">Hey <%= current_user.name%></p>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
            </li>
            <% else %>
            <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
            <% end %>
        </ul>
    </nav>
</header>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Philosopher:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", async: true %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "application" %>
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
       <!-- Other meta tags and stylesheets -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
   </head>

   <body id = "library">
      <div id = "container">
         
       <header id="header">
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path%>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
</header>

         <div id = "content">
            <%= yield -%>
         </div>
         
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
   </body>
   
</html>